// This file is generated by Slice Machine. Update with care!

import Carousel from './Carousel';
import Figure from './Figure';
import Section from './Section';

export {
	Carousel,
	Figure,
	Section,
};

export const components = {
	carousel: Carousel,
	figure: Figure,
	section: Section,
};
