import Head from 'next/head'

import Card from 'components/Card'
import GradientBg from 'components/Gradient'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next Project Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <GradientBg />
      <main>
        <Card />
      </main>
    </div>
  )
}
